name: 'snowflake_tpch_demo'
version: '1.0.0'
config-version: 2

profile: 'snowflake_tpch_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  snowflake_tpch_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
