version: 2

models:
  - name: stg_orders
    description: "Orders joined with customers, with derived columns"
    columns:
      - name: o_orderkey
        tests:
          - unique
          - not_null

  - name: customer_revenue
    description: "Aggregated revenue per customer"
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: customer_revenue_by_year
    description: "Aggregated yearly revenue per customer"
    columns:
      - name: customer_id
        tests:
          - not_null
      - name: order_year
        tests:
          - not_null
