version: 2


sources:
- name: tpch_sf1
database: SNOWFLAKE_SAMPLE_DATA
schema: TPCH_SF1
tables:
- name: customer
description: "TPCH customer table (raw)"
- name: orders
description: "TPCH orders table (raw)"
- name: lineitem
description: "TPCH lineitem table (raw)"


models:
- name: stg_orders
description: "Silver model: orders enriched with customer name and derived columns"
columns:
- name: o_orderkey
description: "Primary order key"
tests:
- unique
- not_null
- name: o_custkey
description: "Customer key"
- name: order_year
description: "Derived order year"


- name: customer_revenue
description: "Gold model: aggregated revenue per customer"
columns:
- name: c_custkey
description: "Customer key"
tests:
- not_null
- name: customer_name
description: "Customer name"
- name: total_revenue
description: "Sum of extendedprice*(1-discount)"